### PR TITLE
Updates to course setup page

### LINKED ISSUE #53: Emphasize knowing bash/terminal as requirement - or point to online resources about it

### LINKED ISSUE #54: When explaining GitKraken, mention they can use GitHub Desktop, just buttons and functionality will be different. Clarify that GitKraken is cross-platform, and that is why we are using it

### LINKED ISSUE #55: Mention in the setup that GitKraken will be installed later on, so they are ready for it

### LINKED ISSUE #56: Create a GitHub account during the setup (nothing else). PAT configuration, if needed will be done later

### PR DESCRIPTION
**Pull request by dc2917**
Similar to #49 but without wrapping each OS's installation instructions in \<details> tags, since the section folding is not rendered properly in the build.

---

This PR adds some improvements to the course setup page:

* Mention the option of setting up GitHub (account + authentication) and installing GitKraken ahead of the course
* Remind attendees of the prerequisites.
* Fix some formatting in the install instructions

Closes #53 
Closes #54 
Closes #55 
Closes #56

### CODE REVIEW

**Review by AdrianDAlessandro — APPROVED** [review]
Thanks for tagging me here! The changes look good. If you want to make those sections collapsable, I found a fix for it. You need to wrap what's inside the `<details>` element in a div that you label as markdown. So:

```markdown
<details>
  <summary><strong>Windows</strong></summary>
  <div markdown=1>
1. Don't indent these
   2. Do indent these
  </div>
</details>
```

Renders correctly for me locally
Screenshot 2024-10-09 at 14 59 31

**Comment by AdrianDAlessandro** [comment]
Ignore that, I found a better solution!

**Comment by dc2917** [comment]
> Thanks for tagging me here! The changes look good. If you want to make those sections collapsable, I found a fix for it. You need to wrap what's inside the `<details>` element in a div that you label as markdown. So:

Not working for me:

```md
<details>
  <summary><strong>Windows</strong></summary>
  <div markdown=1>
1. Download the Git for Windows [installer](https://git-for-windows.github.io/).
1. Run the installer and follow the steps below:
   1. Click on "Next" four times (two times if you've previously installed Git). You don't need to change anything in the Information, location, components, and start menu screens.
   1. From the dropdown menu select "Use the nano editor by default" and click on "Next".

...

  </div>
</details>


![image](https://github.com/user-attachments/assets/613e2501-08d9-4ebe-ad76-f5ae490cfb63)

**Comment by AdrianDAlessandro** [comment]
> Ignore that, I found a better solution!

Sorry for the delay, was testing it out. The short answer is use the `.solution` blockquote (see [sw carpentry guide](https://carpentries.github.io/lesson-example/04-formatting/index.html#special-blockquotes))

The long answer is check what I did here https://github.com/ImperialCollegeLondon/intermediate_grad_school_git_course/pull/73

**Comment by dc2917** [comment]
> > Ignore that, I found a better solution!
> 
> Sorry for the delay, was testing it out. The short answer is use the `.solution` blockquote (see [sw carpentry guide](https://carpentries.github.io/lesson-example/04-formatting/index.html#special-blockquotes))
> 
> The long answer is check what I did here [ImperialCollegeLondon#73](https://github.com/ImperialCollegeLondon/intermediate_grad_school_git_course/pull/73)

Ah nice, thanks!
And no worries, the 👀 was more with excitement than impatience 😅

**Pull request merged**
