### PR TITLE
Review of main pages (README.md, index.md, handouts)

### LINKED ISSUE #6: Update main pages, including the README, index etc. to reflect new course title, content and aims

### PR DESCRIPTION
**Pull request by dc2917**
I have updated these to reflect the updates to this course and the existence of the intermediate course. Relevant changes are largely just title changes and links/references to the intermediate course, as well as new bullet points on the index relating to the new content, and some minor changes have been made for consistency with updated material.

Closes #6

### CODE REVIEW

**Review by dalonsoa — APPROVED** [review]
I've just made a minor suggestion. 

Honestly, I did not know we had Latex handouts. We should check if they are on sync or not with the course material. Could you open an issue so we don't forget this?

**Review by alexdewar — CHANGES_REQUESTED** [review]
I've spotted a few minor things, but otherwise all good.

I tried building the handouts as a sanity check and they compile fine for me. I guess maybe we could add a `.gitignore` and `Makefile` to the `handouts/` folder? This could be a separate issue.

**Comment by alexdewar** [comment]
PS -- It seems like most of the links in ``common.tex`` are dead. Maybe we need an issue for it?

Do we want to go to the extent of having the CI system checking for dead links like we do elsewhere?

**Comment by alexdewar** [comment]
> I've spotted a few minor things, but otherwise all good.
> 
> I tried building the handouts as a sanity check and they compile fine for me. I guess maybe we could add a `.gitignore` and `Makefile` to the `handouts/` folder? This could be a separate issue.

I spoke too soon. It looks like you can already do `make handouts` from the root and it'll build them using latex on docker. Pretty neat.

**Pull request merged**
